FROM hub-mirror.c.163.com/library/ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y --no-install-recommends \
    openssh-server rsync curl wget sudo && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash revlay-user && \
    echo "revlay-user:revlay-password" | chpasswd && \
    adduser revlay-user sudo

RUN mkdir /var/run/sshd
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"] 